// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRN4lKzTAzyc2R4750sNbQD9dswwXbx6A',
    appId: '1:522793099309:web:52f283a4864d08eb0498a4',
    messagingSenderId: '522793099309',
    projectId: 'applicationtripsflutter',
    authDomain: 'applicationtripsflutter.firebaseapp.com',
    storageBucket: 'applicationtripsflutter.appspot.com',
    measurementId: 'G-YYSL5GV928',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAofBvXw4_CdeQ4qQ9I7HpwLZZvcQV8jg',
    appId: '1:522793099309:android:a4bb979bb87956c50498a4',
    messagingSenderId: '522793099309',
    projectId: 'applicationtripsflutter',
    storageBucket: 'applicationtripsflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRrueTVrS42Gvp9J5rAfLX8T-X_BgbRPY',
    appId: '1:522793099309:ios:431b162d5631225a0498a4',
    messagingSenderId: '522793099309',
    projectId: 'applicationtripsflutter',
    storageBucket: 'applicationtripsflutter.appspot.com',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRrueTVrS42Gvp9J5rAfLX8T-X_BgbRPY',
    appId: '1:522793099309:ios:e3fd929a1fffbb0c0498a4',
    messagingSenderId: '522793099309',
    projectId: 'applicationtripsflutter',
    storageBucket: 'applicationtripsflutter.appspot.com',
    iosBundleId: 'com.example.application.RunnerTests',
  );
}
