name: application
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cached_network_image: ^3.1.0
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  google_sign_in: ^6.1.6
  image_picker: ^1.0.7
  generic_bloc_provider: ^2.0.0-nullsafety.1



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
     - assets/img/person.jpeg
     - assets/img/perfil1.jpeg
     - assets/img/perfil2.jpeg
     - assets/img/perfil3.jpeg
     - assets/img/perfil4.jpeg
     - assets/img/arbol.jpeg
     - assets/img/lago.jpeg
     - assets/img/montaña.jpeg
     - assets/img/muelle.jpeg
     - assets/img/rio.jpeg
     - assets/img/selva.jpeg
     - assets/img/profile.jpg


  fonts:
     - family: Lato
       fonts:
         - asset: fonts/Lato-Regular.ttf